export const AUTH_CONSTANTS = {
  ACCESS_TOKEN_EXPIRES_IN: "15m",
  REFRESH_TOKEN_EXPIRES_IN: "7d",
  PASSWORD_RESET_EXPIRES_IN: 60,
  EMAIL_VERIFICATION_EXPIRES_IN: 24 * 60,
  MIN_PASSWORD_LENGTH: 8,
} as const;
