export default {
  preset: "ts-jest",
  testEnvironment: "node",
  roots: ["<rootDir>/src"],
  testMatch: ["**/__tests__/**/*.test.ts", "**/?(*.)+(spec|test).ts"],
  moduleNameMapper: {
    "^@hds/core$": "<rootDir>/../../packages/core/src",
    "^@hds/infrastructure$": "<rootDir>/../../packages/infrastructure/src",
    "^@hds/shared$": "<rootDir>/../../shared/src",
  },
  collectCoverageFrom: [
    "src/**/*.ts",
    "!src/**/*.d.ts",
    "!src/**/*.test.ts",
    "!src/**/*.spec.ts",
    "!src/**/index.ts",
    "!src/main.ts",
    "!src/server.ts",
    "!src/config/**",
    "!src/middlewares/**",
    "!src/**/*.routes.ts",
    "!src/**/*.dto.ts",
  ],
  coverageDirectory: "coverage",
  coverageReporters: ["text", "lcov", "html"],
  coverageThreshold: {
    global: {
      branches: 60,
      functions: 60,
      lines: 60,
      statements: 60,
    },
  },
  setupFilesAfterEnv: ["<rootDir>/../../tests/setup/jest.setup.ts"],
  clearMocks: true,
  resetMocks: true,
  restoreMocks: true,
};
